print("============Desafio 9============")
var = int(input('Digite um número inteiro: '))
print('A tabuada do {} é:'.format(var))
print('-'*15)
print('{0} x  1 = {1} \n{2} x  2 = {3} \n{4} x  3 = {5} \n{6} x  4 = {7} \n{8} x  5 = {9}'.format(var, var*1, var, var*2, var, var*3, var, var*4, var, var*5))
print('{0} x  6 = {1} \n{2} x  7 = {3} \n{4} x  8 = {5} \n{6} x  9 = {7} \n{8} x 10 = {9}'.format(var, var*6, var, var*7, var, var*8, var, var*9, var, var*10))
print('-'*15)