print("============Desafio 4============")
n = input('Digite algo: ')
print('O tipo é:', type(n))
print('Upper:', n.isupper())
print('Alnum:', n.isalnum())
print('Alpha:', n.isalpha())
print('Numeric:', n.isnumeric())
print('Ascii:', n.isascii())
print('Decimal:', n.isdecimal())
print('Digit:', n.isdigit())
print('Identifier:', n.isidentifier())
print('Lower:', n.islower())
print('Printable:', n.isprintable())
print('Space:', n.isspace())
print('Title:', n.istitle())